name = "sparkfun-qwiic-motor-driver"
description = "Interface to the SparkFun Qwiic motor driver."
version = "0.1.0"

authors = ["Karsten Lueth"]
maintainers = ["Karsten Lueth <kl@kloc-consulting.de>"]
maintainers-logins = ["KLOC-Karsten"]
licenses = "BSD-3-Clause"
website = "https://github.com/KLOC-Karsten/sparkfun-qwiic-motor-driver"
tags = ["hal", "motor-driver", "sparkfun", "i2c"]


[[depends-on]]
hal = "^1.0.0"
