name = "grove_i2c_motor_driver"
description = "Interface to the Grove I2C motor driver."
version = "0.1.0-dev"

authors = ["Karsten Lueth"]
maintainers = ["Karsten Lueth <kl@kloc-consulting.de>"]
maintainers-logins = ["KLOC-Karsten"]
licenses = "BSD-3-Clause"
website = "https://github.com/KLOC-Karsten/sparkfun-qwiic-motor-driver"
tags = ["hal", "motor-driver", "grove", "i2c"]


[[depends-on]]
hal = "^1.0.0"
